### ISSUE TITLE
Prepare for porter v1 release

### ISSUE THREAD

**Issue by VinozzZ** [getporter/operator#115]
Porter is preping for its v1 release, the operator should follow below steps to prep itself:

- update/test the operator with the current latest porter release
- update/test the operator with the v1-rc once it's ready
- update to use porter v1 once it's ready
- update our docs to mention the most recent version of porter (soon to be rc.1) in the installation and quickstart documents

**Comment by carolynvs** [comment]
Let's make sure to update our docs to mention the most recent version of porter (soon to be rc.1) in the installation and quickstart documents.
