### ISSUE TITLE
Add document for plugin install feature

### ISSUE THREAD

**Issue by VinozzZ** [getporter/operator#122]
We need to have a doc page that explains how to configure plugins through agent config. It should also points out where are the default values are set in both the controller code and the installer bundle

**Comment by carolynvs** [comment]
We would like a dedicated page for configuring the porter agent, like a administrative task page. If we are inspired a concept page that explains what the porter agent is too.

**Comment by carolynvs** [comment]
We need to document how "latest" and not specifying a version impacts how long a porter agent volume is cached and how that can cause problems.

See https://github.com/getporter/operator/issues/134 which would address the problem. For now we at least need to document it.
