### ISSUE TITLE
Ability to install multiple plugins defined in one agent config

### ISSUE THREAD

**Issue by VinozzZ** [getporter/operator#123]
the current code has not solved how to install multiple porter plugins with one agent job. From my discovery, currently porter currently does not seem to allow installation for multiple plugins with one command.

**Comment by VinozzZ** [comment]
From my discovery, I have found three potential solutions to this issue:
 - In one agent job, create a container for each plugin installation
 - Add functionality in porter agent so that it can execute multiple porter command sequentially
    since the plugin config is defined in agent config file, I'm leaning towards to have the agent to handle the installation
 - Add functionality in porter directly to allow multiple plugins being installed with one command
    maybe this can be a command like `porter plugins install -f plugins.yaml' ?

**Comment by carolynvs** [comment]
I vote for updating porter plugins install be able to accept a file so we can install multiple plugins with a single command

**Comment by sgettys** [comment]
I also vote for the plugins install accepting a file kind of like python requirements.txt. If that's a larger effort then having the agent installation of multiple plugins as individual porter commands is a good enough temporary solution!
