### ISSUE TITLE
Proposal: Remove resource level config overrides

### ISSUE THREAD

**Issue by carolynvs** [getporter/operator#154]
**What design is being proposed?**
Remove InstallationSpec.AgentConfig and InstallationSpect.PorterConfig.

**Additional Context**
As we are working on the grpc service to connect outputs from an installation back into kubernetes and allow people to drive events based on when a bundle completes and publishes its outputs, we have realized that letting an installation have config overrides makes it very difficult to select the correct configuration for any one grpc request. Requests always know what namespace they are associated with but do not always have an installation associated to it.

Installation level overrides was a feature I added because it seemed nice, but wasn't driven by a hard requirement or request from anyone. So I'd like to survey our users and see if we can make this change before v1 so that the grpc service can integrate with the operator well.

**Risks/Concerns**
It's not clear yet if anyone relies on this feature.

**What other approaches were considered?**
Adding installation or config references to every grpc call.

**Implementation details**
N/A

# Checklist
- [x] This proposal has remained open for at least one week, to allow time for community feedback.

**Comment by carolynvs** [comment]
There was no comments here or in meetings so I am going to remove resource level PorterConfig overrides from the operator. The title originally only mentioned installations but ParameterSet/CredentialSet.

❓ AgentAction also has PorterConfig which I'm not sure if we want to keep that or not. @sgettys @bdegeeter Do you recall if during your work on the grpc service having PorterConfig on AgentAction (which allows someone to run an arbitrary porter command with a custom configuration file) is problematic?

**Comment by sgettys** [comment]
> There was no comments here or in meetings so I am going to remove resource level PorterConfig overrides from the operator. The title originally only mentioned installations but ParameterSet/CredentialSet.
> 
> ❓ AgentAction also has PorterConfig which I'm not sure if we want to keep that or not. @sgettys @bdegeeter Do you recall if during your work on the grpc service having PorterConfig on AgentAction (which allows someone to run an arbitrary porter command with a custom configuration file) is problematic?

At this point we haven't plumbed the grpc service into the operator so no issues around AgentAction. The current implementation is just running the grpc service as a standalone Deployment which specifies a porter config via a volume mount. Once this is managed by the operator it can use the same workflow as installations for managing the porter config
