### ISSUE TITLE
Copy all labels from the installation to generated resources

### ISSUE THREAD

**Issue by carolynvs** [getporter/operator#25]
Let the user configure additional settings on the job spawned by the Porter Operator to run Porter commands. One use of that we can set the necessary labels for pod identity.

The AgentConfig struct needs to support passing additional labels and annotations.

**Comment by carolynvs** [comment]
I've updated the title to reflect that we just want to copy labels from the installation resource to any generated resources (job, pvc, secret). There has been a bunch of refactoring at this point and I think the change should be very straightforward now.

**Comment by sgettys** [comment]
@carolynvs  Isn't this closed now?

**Comment by carolynvs** [comment]
Yup!
