### ISSUE TITLE
Document the operator on Porter's website

### ISSUE THREAD

**Issue by carolynvs** [getporter/operator#30]
- [x] Requirements
- [x] How to install
- [x] Explain what runs where
- [x] Quickstart with install, upgrade version and uninstall
- [x] AgentConfig
- [x] PorterConfig
- [ ] #144
- [x] Using with the porter cli - this is explained in contributing.md but not on the website

**Comment by JeremyGHutchins** [comment]
Can you please add information about using parameters.  For example, we have a bundle that we have authored which has a parameter of type "file".  Not sure how to pass this in, given that the `parameters` in the CRD is just a map[string]string.

**Comment by carolynvs** [comment]
There may be a workaround now for file. I threw out one idea to @donmstewart where we can try setting the parameter type to string and the contentEncoding to base64. I haven't verified it myself to know for sure if it will work. We may need a fix to Porter so that when the parameter is written out to a file, we decode the string first.

I think we are missing a more k8s native way to provide a file, for example being able to make a parameter set where the source of the parameter is a k8s secret or config map.

**Comment by carolynvs** [comment]
I have created sub issues for remaining tasks and assigned them to the v1 milestone. Closing this issue in favor of the more specific task issues.
