### ISSUE TITLE
How to upgrade the porter operator from within K8s

### ISSUE THREAD

**Issue by JeremyGHutchins** [getporter/operator#32]
It appears that the porter operator requires bundles to be `install`ed before `upgrade`ing.  We are trying to bootstrap ourselves into a "kubernetes exclusive" mode, but in that case, after running `porter install porterops ...` from the CLI to get the porter operator installed (and then using it to install the rest of our wares), we have no way to porter upgrade the porter operator itself from within K8s (since it was not installed from the operator).  Is there a way to do such a thing?

**Comment by carolynvs** [comment]
At the moment? No, but it is something that we need to do! 😅 

What I am thinking is that when porter operator is installed with a bundle, we will add an installation CR for the operator itself. If the backing storage for the operator doesn't have a record for the installation (i.e. a claim), we can insert it at the same time.

So the bundle will handle creating the necessary records for managing the operator using the porter operator going forward.

**Comment by AGMETEOR** [comment]
Hey @troy0820 could I get assigned this?

**Comment by schristoff** [comment]
Fixed in #270
