### ISSUE TITLE
Cannot import operator api into go project

### ISSUE THREAD

**Issue by JeremyGHutchins** [getporter/operator#35]
I have an operator I'm writing in golang.  I want to be able to submit porter.sh/installation CRs.  If I try using `get.porter.sh/operator` in my go.mod, I get...

`unrecognized import path "get.porter.sh/operator": reading https://get.porter.sh/operator?go-get=1: 404 Not Found`

if I try using `github.com/getporter/operator` instead, then I get...

`parsing go.mod:
	module declares its path as: get.porter.sh/operator
	        but was required as: github.com/getporter/operator`

I think you're missing a redirect on `get.porter.sh/operator` -> `github.com/getporter/operator`?

**Comment by carolynvs** [comment]
Thanks for pointing this out! Should be fixed as soon as this is merged. https://github.com/getporter/vanity/pull/15

**Comment by JeremyGHutchins** [comment]
Thanks for the speedy turnaround, @carolynvs !
