### ISSUE TITLE
PorterConfigSpec doesn't honor optional fields

### ISSUE THREAD

**Issue by sgettys** [getporter/operator#83]
The ToPorterDocument fails for PorterConfigSpec when the "config" field is not provided as part of the secrets or storage config: Example:

`PorterConfigSpec{
  DefaultStoragePlugin: pointer.StringPtr("mongodb"),
  DefaultSecretsPlugin: pointer.StringPtr("kubernetes.secrets"),
  DefaultStorage:       pointer.StringPtr("in-cluster-mongodb"),
  Storage: []StorageConfig{
    {PluginConfig{
      Name:         "in-cluster-mongodb",
      PluginSubKey: "mongodb",
    }},
  },
}
`
or 
`PorterConfigSpec{
  DefaultStoragePlugin: pointer.StringPtr("mongodb"),
  DefaultSecretsPlugin: pointer.StringPtr("kubernetes.secrets"),
  DefaultSecrets:       pointer.StringPtr("kubernetes-secrets"),
  Secrets: []SecretsConfig{
    {PluginConfig{
      Name:         "kubernetes-secrets",
      PluginSubKey: "kubernetes.secrets",
    }},
  },
}`

Should both be valid porter config specs and generate a Porter Document but both fail the marshal the PluginConfig with the following error:

Error:      	Received unexpected error:
            	            	unexpected end of JSON input
            	            	could not marshal the plugin config to json
            	            	get.porter.sh/operator/api/v1.PluginConfig.MarshalYAML

**Comment by carolynvs** [comment]
Fixed by #82
